### ISSUE TITLE
Test run (and real data run) crashes on 'unknown aesthetic: outfit'

### ISSUE THREAD

**Issue by defleury** [ohlab/GRiD#1]
Hi @ohlab,

I've read the paper on `GRiD` with great interest, and have been playing with the tool to analyse some data I'm working on. I installed from bioconda and have the latest version `1.2`.

I encounter the following runtime error, both when running the tutorial set, and when trying real data:

```
Loading required package: proto
Warning message:
no DISPLAY variable so Tk is not available 
Warning: Ignoring unknown aesthetics: outfit
Error in filter_impl(.data, quo) : 
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.
Calls: %>% ... as.data.frame -> filter -> filter.tbl_df -> filter_impl -> .Call
Execution halted
```

I've looked into the code directly, but have been unable to debug this myself. Do you have an idea what might be causing this issue?

**Comment by aemiol** [comment]
Hi @defleury, it appears you have an older version of the r library dplyr. Can you try updating to a newer version of dplyr using "conda update r-dplyr" and re-run the example test?
