### ISSUE TITLE
Question on Pathoscope

### ISSUE THREAD

**Issue by santoshe1** [ohlab/GRiD#10]
Hi Team,

I had a question regarding the GRiD Results. I used GRiD with and without Pathoscope option. I find that the number of genomes identified by using Pathoscope is really low in comparison to GRiD without Pathoscope for multiple samples. For ex, I get about 65 genomes only identified using Pathoscope where as I get about 1000+ genomes without it. Also, is GRiD with -P only considered only for ambiguous reads ?? Could I merge this results while using it without -P option??

Thank you

**Comment by santoshe1** [comment]
I also observe that results are totally different on using Pathoscope and not?

**Comment by aemiol** [comment]
Hi,
This is totally expected. If you have a read mapping to multiple genomes, Pathoscope identifies the most likely genome where the read comes from. Thus, you will have much less genomes using the -p option. 

You can find out more about Pathoscope from https://sourceforge.net/p/pathoscope/wiki/Home/

Regards,
Tunde

**Comment by aemiol** [comment]
Hi,
This is totally expected. If you have a read mapping to multiple genomes, Pathoscope identifies the most likely genome where the read comes from. Thus, you will have much less genomes using the -p option. 

You can find out more about Pathoscope from https://sourceforge.net/p/pathoscope/wiki/Home/

Regards,
Tunde

**Comment by santoshe1** [comment]
Thank you for the quick response Dr. Tunde. Would it be then better to consider only the results from Pathoscope if you suspect to have more ambiguous reads?

**Comment by aemiol** [comment]
Yes. I will accept the results with Pathoscope since it is unlikely there will be over 1000 different species in a sample (as you saw without Pathoscope).

Cheers,
Tunde

**Comment by santoshe1** [comment]
Thank you again for your response Dr. Tunde. I have one more question, I have read your paper and it mentions you have observed Propionibacterium acne in one of the results. However, I am unable to find the same organism in the metadata of the database_misc.txt file. Could you please help me out and provide if you have any other detailed metadata file for the genomes/species_strain information?

**Comment by aemiol** [comment]
Propionibacterium acnes is now scientifically referred to as "Cutibacterium acnes". You should find that in database_misc.txt
