### ISSUE TITLE
GRiD value impacted by sequencing depth ?

### ISSUE THREAD

**Issue by YU-DENG** [ohlab/GRiD#11]
Hi,

I am using GRiD to evaluate growth rates of metagenome assembled genomes in multiple samples, metagenomic sequencing depth for samples varies a lot, so I am wondering whether should I subset all the metagenomic datasets to an even depth. 

Thanks a lot !

**Comment by aemiol** [comment]
Typically, higher coverage results in more accurate predictions and factors such as genome fragmentation may affect the output. I think you should be ok with genome coverage >= 1X.

Cheers,
Tunde
