### ISSUE TITLE
Issue report: Fatal error: cannot open file 'check_R_libraries.R': No such file or directory

### ISSUE THREAD

**Issue by zhssakura** [ohlab/GRiD#12]
Dear @ohlab,

I have installed GRiD on MacOS system with conda environment. When I was trying to test with example data, I encountered an error as following:
`
(GRiD)zzfanyi-MacBook-Pro:test zzfanyi$ grid single -r . -g S_epidermidis.LRKNS118.fna -o output_single
` 

readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
single option activated
/Users/zzfanyi/Bioinfo/software/GRiD-master/test is present directory
 is the reads directory
 is the output directory
 is the path to reference genome
 ################ Checking for dependencies ########
parallel found
R found
bowtie2 found
seqtk found
samtools found
bedtools found
bamtools found
blastn found
pathoscope found
All required packages found
 ################ Checking for required R libraries ########
Fatal error: cannot open file 'check_R_libraries.R': No such file or directory
R libraries ok
rm: .checkedR: No such file or directory
usage: mkdir [-pv] [-m mode] directory ...
Output directory not Empty

I do not know why this issue happens. Could you please help me with it? Thank you very much!

Best,

Shan

**Comment by aemiol** [comment]
Hi Shan,

This has to do with a dependency in the latest version of GRiD (mosdepth) that is currently unavailable via conda for macOS. Please refer to this thread on ways to circumvent this issue. https://github.com/ohlab/GRiD/issues/3
 
Regards,
- Tunde

**Comment by zhssakura** [comment]
Hi Tunde,

Thanks for your quick reply. I can install GRiD 1.2 on the Unix system and it works well on example test. But I could not install GRiD 1.3. I wish this will be solved in the future. Thank you again!

Best,

Shan
