### ISSUE TITLE
Are GRiD results different between parallel and simultaneous processing?

### ISSUE THREAD

**Issue by TaskeHAMANO** [ohlab/GRiD#13]
Hello, I really appreciate providing such a wonderful tool.

I am trying to use GRiD by multiplex mode with provided stool database for about 100~ samples. At this time, there are two ways to use GRiD, parallelly giving the directory path of each sample or specifying the path containing all samples to -r. I would like to adopt the former because of computational time. However, if GRiD uses some information that is shared between samples, the result may be changed. 

When I read the paper, it seems that there is no such thing, but how is it?

**Comment by aemiol** [comment]
GRiD results should not be different if you process the reads simultaneously or in parallel. I recommend with parallel, taking advantage of the -l flag to specify a file that lists a subset of reads for processing.

Regards,
Tunde

**Comment by TaskeHAMANO** [comment]
OK, I will do it one by one.
thanks!
