### ISSUE TITLE
Units of GRiD values

### ISSUE THREAD

**Issue by franciscozorrilla** [ohlab/GRiD#14]
Hello, I have a short question about the interpretation/meaning of the GRiD values. The publication states that GRiD stands for Growth Rate Index, but there is no explicit mention of the units of this growth rate index. Could you confirm that (refined) GRiD values have units of 1/hour?

Thanks and best wishes,
Francisco

**Comment by aemiol** [comment]
GRiD values are unitless. It is simply the ratio of reads count at the ori vs terminus region which is proportional to growth rate.

Cheers,
Tunde

**Comment by franciscozorrilla** [comment]
I see, that makes sense. 
The reason why I ask is because I am generating genome scale metabolic models out of metagenome assembled genomes, and I was hoping to be able to use refined GRiD values as approximations for the growth rates of individual members in community flux balance analysis simulations, which is generally in units of 1/hour.
Would you advise against this usage of GRiD values?

Best wishes,
Francisco

**Comment by aemiol** [comment]
Like I mentioned earlier, GRiD values are correlated with growth rate. If you absolutely need values in units of 1/hr, then GRiD isn't appropriate.

Cheers,
Tunde

**Comment by franciscozorrilla** [comment]
I understand, thank you for your responses.

Best wishes,
Francisco
