### ISSUE TITLE
Segmentation fault/core-dumping problem

### ISSUE THREAD

**Issue by Anto007** [ohlab/GRiD#16]
Hi, 

I'm running your cool GRiD tool through conda and I get the below segmentation fault at the bedtools step. I generated the sam file using bbmap tool and I was running GRiD on a node with 100G memory. I would very much appreciate any inputs on how best to fix this issue. Thanks! 

################ Checking for dependencies ########
parallel found
R found
bowtie2 found
seqtk found
samtools found
bedtools found
bamtools found
blastn found
pathoscope found
mosdepth found
All required packages found
 ################ Checking for required R libraries ########
R libraries ok
Output directory ok
Creating bowtie index
done
Running BLAST to dnaA and dif databases
done
ERR3230147_bin.2_5Kbtrim
[samopen] SAM header is present: 322 sequences.
/ibex/scratch/anto/conda_grid_env/bin/grid: line 378: 284144 Segmentation fault      (core dumped) bedtools bamtofastq -i $ODR/$i.temp.bam -fq $ODR/$i.MAP.fastq

**Comment by aemiol** [comment]
I'm not sure exactly but I suspect it might be memory-related. Could you test run a smaller sam input file?

Cheers,
Tunde

**Comment by Anto007** [comment]
Many thanks for your prompt response. I increased the memory to 256G and provided a much smaller sam file (31 Mb; my last one was 99Mb) and yet I get the same error message: 
/ibex/scratch/anto/conda_grid_env/bin/grid: line 378: 284144 Segmentation fault (core dumped) bedtools bamtofastq -i $ODR/$i.temp.bam -fq $ODR/$i.MAP.fastq

**Comment by Anto007** [comment]
Instead of using the sam file, I now tried using just one of the reads (forward.fastq.gz) of my paired-end read set and I am indeed getting the GRiD scores estimated but what I'm slightly worried about is whether this approach is correct? Also, while GRiD gives me an replication index of 1.24, iRep is giving me an index of 1.87 for the same bin (which happens to have high coverage and % relative abundance of 14.63% among all bacterial MAGs in the library)
