### ISSUE TITLE
ggplot build error

### ISSUE THREAD

**Issue by susheelbhanu** [ohlab/GRiD#17]
Hi, 

I'm running a grid single command as follows and get the following error: 

`grid single -r . -e fastq -o grid_output -g ../B12_maxbin.001.contigs.fa-fixed.fa -n 2`

```
Loading required package: proto
Warning message:
no DISPLAY variable so Tk is not available
Warning: Ignoring unknown aesthetics: outfit
Error in if (zero_range(as.numeric(limits))) { :
  missing value where TRUE/FALSE needed
Calls: ggplot_build ... <Anonymous> -> f -> <Anonymous> -> f -> <Anonymous> -> f
Execution halted
```

Any thoughts on why this is occuring?

Thank you!

**Comment by aemiol** [comment]
Hi,
It seems the genome coverage in that sample is zero or too low. 

Cheers,
Tunde

**Comment by susheelbhanu** [comment]
Hi Tunde, 

How is the genome coverage calculated? Because I used a different coverage estimation method, and according to it, the same is 12X. 

Could you please clarify?

Thanks!

**Comment by aemiol** [comment]
Could you confirm that majority of your contigs have coverage > 0?

**Comment by susheelbhanu** [comment]
Hi, 

Please see attached the contigs coverage file. 

Thank you!
[B12_maxbin.001.contigs.fa.txt](https://github.com/ohlab/GRiD/files/4119093/B12_maxbin.001.contigs.fa.txt)

**Comment by aemiol** [comment]
> Hi,
> 
> Please see attached the contigs coverage file.
> 
> Thank you!
> [B12_maxbin.001.contigs.fa.txt](https://github.com/ohlab/GRiD/files/4119093/B12_maxbin.001.contigs.fa.txt)

Hi, it is not clear what the columns are in the attached file. What are they? I assume the 2nd column is contig length. Right?

**Comment by susheelbhanu** [comment]
yeah sorry.. the 2nd is length and the 3rd the coverage per contig

**Comment by aemiol** [comment]
Is there a way you can send across the fastq file and in question and also the genome?

**Comment by susheelbhanu** [comment]
Thanks.. i'm on a train at the moment, so will send them to you Wednesday, if that's ok?! thanks again for the help!

**Comment by aemiol** [comment]
> Thanks.. i'm on a train at the moment, so will send them to you Wednesday, if that's ok?! thanks again for the help!

Sure. Send it whenever you are ready
