### ISSUE TITLE
generating custum databases for grid multiplex mode

### ISSUE THREAD

**Issue by till-bornemann** [ohlab/GRiD#2]
Hi,
I would like to use the 'grid multiplex' mode with custom genome databases instead of extending on the ones you supply. Can you use the update_database command to also generate new databases instead of extending on existing ones? When I tried using a database generated like this, I mostly get GRiD values between 1.00-1.10 not at all similar to iRep values. In single mode on the other hand, the GRid values make sense. 

Any help is appreciated,
Best regards
Till

**Comment by aemiol** [comment]
Hi Till,
Yes, it is perfectly Ok to use the 'update_database' to create your custom database. In that case, disregard any error warnings you may get.
