### ISSUE TITLE
ggplot_build error in single mode

### ISSUE THREAD

**Issue by NVOostende** [ohlab/GRiD#21]
Dear Oh Lab,

I am running GRiD-1.3 on a linux server in single mode using mapped metagenomic reads to a reference genome.

```
grid single -r ${READS_DIR} -e sam -g "${REFGEN_DIR}/${BIN_NAME}.fa" -o "${GPFS_DIR}" -n $NUM_THREADS
```

Everything seems to work fine until GRID.R starts, that is when I get the following message:
```
Warning message:
no DISPLAY variable so Tk is not available 
Warning: Ignoring unknown aesthetics: outfit
Error in if (zero_range(as.numeric(limits))) { : 
  missing value where TRUE/FALSE needed
Calls: ggplot_build ... <Anonymous> -> f -> <Anonymous> -> f -> <Anonymous> -> f
Execution halted
```
At first I thought maybe the coverage was insufficient but looking at the $coverage variable output it is ~33x.
I plotted the $FILE.main.sam.txt coverage values along the genome as a quick check.
<img width="466" alt="Screen Shot 2020-08-13 at 6 34 57 PM" src="https://user-images.githubusercontent.com/25377760/90161672-c3046e80-dd93-11ea-98b9-1b4cd76ad93a.png">
Not sure what the problem is ...
Any help is much appreciated.

Best,
Nicolas

**Comment by aemiol** [comment]
Hi Nicolas,

What is the contamination level of your bin? Do most of your contig have coverage = 0? Can you send across the "$FILE.main.sam.txt" file?

Thanks
Tunde

**Comment by NVOostende** [comment]
Hi Tunde,

Thank you for your quick reply!

I used a reference genome that was deemed abundantly present in the
metagenomic sample. So not sure about the contamination.
Yes, a lot of zero coverage values in this case. This was by design,
however, as I only used those reads that mapped to bacterial single copy
genes. This explains the gaps in the coverage vs genome location figure.
Here is the link to the main.sam.tx file (~60Mb):
 SCG_NATL1.main.sam.txt
<https://drive.google.com/file/d/1nY3f85DFpq306vZtKHlYYzFz1cu4wTGP/view?usp=drive_web>


Best,
Nicolas

**Comment by aemiol** [comment]
You can see there are plenty of genomic regions with zero coverage. Your approach, using only reads from marker genes, isn't compatible with GRiD since estimates rely on coverage differences across the entire genome landscape. 

Thanks.
Tunde

**Comment by NVOostende** [comment]
I will have to use an alternative method then ..
Thank you for the clarification.
Nicolas
