### ISSUE TITLE
Question on creating custom database

### ISSUE THREAD

**Issue by nattzy94** [ohlab/GRiD#9]
Hi,

I am quite new to coding and running linux packages. I just want to check that I am doing the right thing in creating a custom database. Currently, I am using the following command:

update database -d ./co_growth -g ./co_growth  -p composite

Can I check that this basically generates a custom database that contains the sequences using all the ".fasta" files in "./co_growth"? Also does it still work if I run the command without an existing database in ./co_growth to be updated? 

Thanks and the appreciate the help.

**Comment by aemiol** [comment]
Yes, your current command is ok and should work just fine. You can confirm this from the generated database_misc.txt file  and ensuring the first column lists your genomes. 
 
However, i will encourage you separate the Genomes folder from the database folder. Simply create an empty directory as your database directory.

Regards,
Tunde

**Comment by nattzy94** [comment]
Thanks! Managed to get it to work.

**Comment by nattzy94** [comment]
Sorry, another question, the .pdf heatmap file doesn't seem to work for me. I am testing on a file containing sequences of 2 bacterial species. Could this be the reason why?

**Comment by aemiol** [comment]
Yes. The pdfs are heatmaps created with hierachical clustering. You need at least 3 genomes

**Comment by nattzy94** [comment]
ok thanks!
